### PR TITLE
Add support for template literal

### PR DESCRIPTION
**Pull request by gucong3000**
Closes: #32

### CODE REVIEW

**Comment by daKmoR** [comment]
hey,

nice progress :)
is this up for testing already? or too early?

**Comment by gucong3000** [comment]
@daKmoR merged to v0.17.0

**Comment by AlexWayfer** [comment]
I think stable version (`0.17.0`) should not have pre-released versions in dependencies (`babel` beta).

Should I update our production to beta versions of some packages now?

**Comment by gucong3000** [comment]
> I think stable version (0.17.0) should not have pre-released versions in dependencies

I agree with you. See: #38

**Comment by AlexWayfer** [comment]
> I agree with you. See: #38

Thank you! Great.

**Pull request merged**
